In [3]:
import pandas as pd
df = pd.read_csv("C:/Users/Mamta Rajbhar/Downloads/customer_shopping_behavior.csv")

In [7]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [9]:
# Checking if missing data or null values are present in the dataset
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [10]:
# Imputing missing values in Review Rating column with the median rating of the product category
df["Review Rating"]=df.groupby('Category')["Review Rating"].transform(lambda x: x.fillna(x.median()))

In [11]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [12]:
df.columns = df.columns.str.lower()

In [13]:
df.columns

Index(['customer id', 'age', 'gender', 'item purchased', 'category',
       'purchase amount (usd)', 'location', 'size', 'color', 'season',
       'review rating', 'subscription status', 'shipping type',
       'discount applied', 'promo code used', 'previous purchases',
       'payment method', 'frequency of purchases'],
      dtype='object')

In [15]:
# Renaming columns according to snake casing for better readability and documentation
df.columns = df.columns.str.replace(' ','_')

In [16]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [17]:
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [19]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [21]:
#create a column of age group

labels = ['Young_adult','Adult','Middle_aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [24]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle_aged
1   19  Young_adult
2   50  Middle_aged
3   21  Young_adult
4   45  Middle_aged
5   46  Middle_aged
6   63       Senior
7   27  Young_adult
8   26  Young_adult
9   57  Middle_aged

In [26]:
# create new column purchase_frequency_days

frequency_mapping= {
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [27]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [29]:
df['frequency_of_purchases'].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [30]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [31]:
df=df.drop('promo_code_used',axis=1)

In [32]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [33]:
pip install pymysql sqlalchemy

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: sqlalchemy in d:\anaconda\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in d:\anaconda\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\anaconda\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2
Note: you may need to restart the kernel to use updated packages.

In [35]:
pip install mysql-connector-python sqlalchemy

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.6.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: sqlalchemy in d:\anaconda\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in d:\anaconda\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\anaconda\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading mysql_connector_python-9.6.0-cp313-cp313-win_amd64.whl (16.5 MB)
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
    --------------------------------------- 0.3/16.5 MB ? eta -:--:--
   ------ --------------------------------- 2.6/16.5 MB 11.2 MB/s eta 0:00:02
   ------------ --------------------------- 5.0/16.5 MB 11.2 MB/s eta 0:00:02
   -------------- ------------------------- 6.0/16.5 MB 10.9 MB/s eta 0:00:01
   -------------- ------------------------- 6.0/16.5 MB 10.9 MB/s eta 0:00:01
   -------------- ------------------------- 6.0/16.5 MB 10.9 MB/s eta 0:00:01
   --------------- ------------------------ 6.3/16.5 MB 5.2 MB/s eta 0:00:02
   --------------- ------------------------ 6.6/16.5 MB 4.8 MB/s eta 0:00:03
   --------------- ------------------------ 6.6/16.5 MB 4.8 MB/s eta 0:00:03
   ----------------- ---------------------- 7.3/16.5 MB 3.8 MB/s eta 0:00:03
   ------------------- -------------------- 7.9/16.5 MB 3.6 MB/s eta 0:00:03
   ----------------------- ---------------- 9.7/16.5 MB 4.1 MB/s eta 0:00:02
   ---------------------------- ----------- 11.8/16.5 MB 4.6 MB/s eta 0:00:02
   -------------------------------- ------- 13.4/16.5 MB 4.8 MB/s eta 0:00:01
   ---------------------------------- ----- 14.2/16.5 MB 4.8 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.5 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.5 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.5 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.5 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.5 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.5 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.5 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.5 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.5 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.5 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.5 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.5 MB 4.9 MB/s eta 0:00:01
   -------------------------------------- - 15.7/16.5 MB 2.8 MB/s eta 0:00:01
   -------------------------------------- - 15.7/16.5 MB 2.8 MB/s eta 0:00:01
   -------------------------------------- - 15.7/16.5 MB 2.8 MB/s eta 0:00:01
   -------------------------------------- - 15.7/16.5 MB 2.8 MB/s eta 0:00:01
   -------------------------------------- - 16.0/16.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 16.5/16.5 MB 2.5 MB/s  0:00:06
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.6.0
Note: you may need to restart the kernel to use updated packages.

In [52]:
#Code for MySQL connecting with PowerBi

from sqlalchemy import create_engine
import pandas as pd  

# MySQL connection
username = "root"
password = "root"
host = "localhost"
port = "3306"
database = "customer_behavior"

# Specify charset explicitly in the connection string to use a supported charset
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}?charset=utf8")

# Write DataFrame to MySQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle_aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young_adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle_aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young_adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle_aged,365